[book]
authors = ["Studio Cherno"]
language = "en"
multilingual = false
src = "src"

[output.html]
theme = "hazel-theme"
default-theme = "Hazel"
google-analytics = "G-0VYYKNCH1P"
additional-css = ["hazel-theme/custom.css", "hazel-theme/hazel-highlight.css"]
smart-punctuation = true
