[book]
authors = ["Studio Cherno"]
language = "en"
multilingual = false
src = "src"

[output.html]
theme = "hazel-theme"
default-theme = "hazel"
additional-css = ["hazel-theme/custom.css", "hazel-theme/hazel-highlight.css"]